meta_product_name: "Trailbooks"
meta_title: "Trailbooks - Plan your trail accommodation"
meta_description: "For self guided hikers to find and reserve mountain huts and campsites on popular trails"
meta_image: "home-banner.jpg" # should exist in `app/assets/images/`
